### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by wes1993** [mishailovic/lampa.py#1]
@mishailovic, sorry if i write here but i can't find this project:
https://github.com/mishailovic/warpy/

Could you help me? I'm really interested

Best Regards
Stefano

**Comment by mishailovic** [comment]
I deleted the repository because cloudflare has fixed the vulnerability.

**Comment by wes1993** [comment]
Thanks a lot for your reply,
I’m using the current version and works very well but no proxy support, can we adapt the code with new?

**Comment by mishailovic** [comment]
Unfortunately I am now very busy with exams, and will be released only for two weeks 😫

**Comment by wes1993** [comment]
Ok no problem if you could share your code I could try do adapt everything :)

**Comment by mishailovic** [comment]
https://github.com/mishailovic/warpy

**Comment by wes1993** [comment]
Thaks a lot!!!
